language: node_js

node_js:
  - 14
  - 12
  - 10

jobs:
  include:
    - stage: release
      node_js: lts/*
      before_deploy: "npx tsc"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
